---
- name: Adding user
  import_playbook: playbook-user.yml

- name: Installing MySQL
  import_playbook: playbook-mysql.yml

- name: Installing Nginx
  import_playbook: playbook-nginx.yml

- name: Installing apps
  hosts: all
  become: true
  vars_files:
    - vars/wordpress_vault.yml    
  roles:   
    - { role: php,  tags: [php, apps] }
    - { role: wordpress, tags: [wp, apps] }

- name: Do some tests
  import_playbook: playbook-tests.yml

